# Generated by Django 4.2.1 on 2023-06-22 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_address_order_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quantiy',
            new_name='quantity',
        ),
    ]
